addressbook/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
import contacts.views

urlpatterns = patterns('',
    url(r'^$', contacts.views.ListContactView.as_view(),
        name='contacts-list',),
    url(r'^new$', contacts.views.CreateContactView.as_view(),
    name='contacts-new',),
    url(r'^edit/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(),
        name='contacts-edit',),    
    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),
        name='contacts-delete',),
    url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(),
        name='contacts-view',),
    url(r'^edit/(?P<pk>\d+)/addresses$', contacts.views.EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^pawan$', contacts.views.HelloView.as_view(),
        name='contacts-edit-addresses',),

)

contacts/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    def __str__(self):
        return ' '.join([self.first_name,self.last_name])

class Address(models.Model): 
    contact = models.ForeignKey(Contact) 
    address_type = models.CharField(max_length=10) 
    address = models.CharField(max_length=255) 
    city = models.CharField(max_length=255) 
    state = models.CharField(max_length=2) 
    postal_code = models.CharField(max_length=20) 

contacts/forms.py
from django.forms.models import inlineformset_factory

from contacts.models import (
    Contact,
    Address,
)

# inlineformset_factory creates a Class from a parent model (Contact)
# to a child model (Address)
ContactAddressFormSet = inlineformset_factory(
    Contact,
    Address,
)

contacts/views.py
# Create your views here.
from django.views.generic import ListView
from contacts.models import Contact
from django.views.generic import CreateView
from django.core.urlresolvers import reverse
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
import forms
from django.http import HttpResponse
from django.views.generic import View


from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class LoggedInMixin(object):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)

class HelloView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse("Hello, World")

class ListContactView(LoggedInMixin,ListView):

    model = Contact
    template_name = 'contact_list.html'


class CreateContactView(LoggedInMixin,CreateView):
    model = Contact
    template_name = 'edit_contact.html'
    def get_success_url(self):
        return reverse('contacts-list')


class UpdateContactView(LoggedInMixin,UpdateView):

    model = Contact
    template_name = 'edit_contact.html'
    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        
        context['action'] = reverse('contacts-edit',
                                    kwargs={'pk': self.get_object().id})


        return context

class DeleteContactView(LoggedInMixin,DeleteView):

    model = Contact
    template_name = 'delete_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')

class ContactView(LoggedInMixin,DetailView):

    model = Contact
    template_name = 'contact.html'

class EditContactAddressView(LoggedInMixin,UpdateView):

    model = Contact
    template_name = 'edit_addresses.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self): 
        return reverse('contacts-list')

contacts/templates/base.html
<html>  
  <body>
  	<h1>Welcome to World of Networking</h1>
  	<div>
      {{ user }}
      {% if user.is_anonymous %}
      <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
      {% else %}
      <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
      {% endif %}
    </div>
  	
    {% block content %}
    {% endblock %}  
    <h2>Thanks</h2>  
  </body>
</html>

contacts/templates/contact.html
{% extends "base.html" %}
{% block content %}
<h1>{{ contact }}</h1>

<p>Email: {{ contact.email }}</p>

<ul>
{% for address in contact.address_set.all %}
   <li>{{ address.address }}<br/>
       {{ address.city }} {{ address.state }}<br/>
       {{ address.postal_code }}
   </li>
{% endfor %}
</ul>
{% endblock %}

contacts/templates/contact_list.html
{% extends "base.html" %}
{% block content %}

<h3>Contacts</h3>

<ul>
  {% for contact in object_list %}
    <li class="contact">
    <a href="{% url "contacts-view" pk=contact.id %}">{{ contact }}</a>
    (<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)


    </li>
  {% endfor %}
</ul>

<a href="{% url "contacts-new" %}">add contact</a>

{% endblock %}

contacts/templates/delete_contact.html
{% extends "base.html" %}
{% block content %}
<h1>Delete Contact</h1>

<p>Are you sure you want to delete the contact {{ contact }}?</p>

<form action="{% url "contacts-delete" pk=contact.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "contacts-list" %}">No, cancel.</a>
</form>
{% endblock %}

contacts/templates/edit_addresses.html
{% extends "base.html" %}
{% block content %}
<h1>Edit Addresses</h1>

<p>Editing addresses for {{ contact }}</p>

<form action="{% url "contacts-edit-addresses" pk=contact.id %}"
      method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {% for address_form in form %}

        <ul>
        {{ address_form.as_ul }}
        </ul>

    {% endfor %}

    <input type="submit" value="Save" />
</form>
{% endblock %}

contacts/templates/edit_contact.html
{% extends "base.html" %}
{% block content %}
{% if contact.id %}
<h1>Edit Contact</h1>
{% else %}
<h1>Add Contact</h1>
{% endif %}
{% if contact.id %}
<a href="{% url "contacts-edit-addresses" pk=contact.id %}">
  Edit Addresses
</a>
<br/>
<a href="{% url "contacts-delete" pk=contact.id %}">Delete</a>
{% endif %}

<form action="{{ action }}" method="POST">
<!--
<h1>Add Contact</h1>

<form action="{% url "contacts-new" %}" method="POST">
-->
  {% csrf_token %}
  <ul>
    {{ form.as_ul }}
  </ul>
  <input id="save_contact" type="submit" value="Save" />
</form>

<a href="{% url "contacts-list" %}">back to list</a>


{% endblock %}